### ISSUE TITLE
Failed to resolve 'kafka:9092': Name or service not known - In docker

### ISSUE THREAD

**Issue by chorsnell** [php-rdkafka/php-rdkafka#112]
I am trying to get php connecting to kafka all within a docker container. Everything is building and running ok, but when I try to connect with the PHP producer, I get the following:

```
httpd_1   | %3|1490816385.542|FAIL|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Failed to resolve 'kafka:9092': Name or service not known
httpd_1   | %3|1490816385.543|ERROR|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Failed to resolve 'kafka:9092': Name or service not known
httpd_1   | %3|1490816385.543|ERROR|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: 1/1 brokers are down
```

I am using the following in PHP
```
        $rk = new RdKafka\Producer();
        $rk->setLogLevel(LOG_DEBUG);
        $rk->addBrokers("kafka");

        $topicConf = new RdKafka\TopicConf();
        $topicConf->set("message.timeout.ms", 1000);
        $topic = $rk->newTopic("DEV", $topicConf);

        $topic->produce(RD_KAFKA_PARTITION_UA, 0, "Message");

        $rk->poll(1000);
        $kafkaConf = new RdKafka\Conf();
        $kafkaConf->setErrorCb(function ($rk, $err, $reason) {
            printf("Kafka error: %s (reason: %s)\n", rd_kafka_err2str($err), $reason);
        });
        $kafkaConf->setDrMsgCb(function ($rk, $message) {
            if ($message->err) {
                print_r($message);
            } else {
                print_r("ok");
            }
        });
```

I've played around, trying to set the host IP in both the docker-compose.yml and the PHP code, but no joy. I also had `connection refused` but I don't know if thats better or worse?

If it helps, my docker-compose.yml
```
httpd:
  build: .
  ports:
  - 8180:80
  volumes:
  - ~/www:/var/www/html
zookeeper:
  image: wurstmeister/zookeeper
  ports:
  - "2181:2181"
kafka:
  build: ~/kafka-docker/.
  links:
  - zookeeper
  ports:
  - "9092:9092"
  environment:
    KAFKA_ADVERTISED_HOST_NAME: kafka
    KAFKA_ADVERTISED_PORT: 9092
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
```
 * PHP version: 7.0.17
 * librdkafka version: 0.9.5.0
 * php-rdkafka version: 2.0.1
