### ISSUE TITLE
HighLevelConsumer: Properly handling broker unavailability and duplicate message reads when commiting in async manner

### ISSUE THREAD

**Issue by mikitafreeman** [php-rdkafka/php-rdkafka#395]
Steps to reproduce:

* push for example 10 messages to a topic.
* run a consumer, processed for example 4 messages.
* "turn of" kafka without restarting a consumer.
```bash
%6|1602837154.254|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: Disconnected (after 44827ms in state UP)
%3|1602837154.255|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: Connect to ipv4#172.24.0.3:9092 failed: Connection refused (after 0ms in state CONNECT)
%4|1602837154.261|FAIL|rdkafka#consumer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/1: Disconnected (after 44835ms in state UP)
%3|1602837154.262|FAIL|rdkafka#consumer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/1: Connect to ipv4#172.24.0.3:9092 failed: Connection refused (after 0ms in state CONNECT)
%3|1602837154.344|FAIL|rdkafka#consumer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/1: Connect to ipv4#172.24.0.3:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
%3|1602837154.358|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: Connect to ipv4#172.24.0.3:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
%3|1602837157.234|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT)
%3|1602837158.224|FAIL|rdkafka#consumer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/1: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT)
%3|1602837188.001|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
%3|1602837188.148|FAIL|rdkafka#consumer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/1: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
%4|1602837200.424|COMMITFAIL|rdkafka#consumer-1| [thrd:main]: Offset commit (manual) failed for 1/1 partition(s): Local: Waiting for coordinator: batchPost[0]@29(Local: Waiting for coordinator)
%3|1602837225.879|FAIL|rdkafka#consumer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/1: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
%3|1602837228.000|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
%4|1602837240.444|COMMITFAIL|rdkafka#consumer-1| [thrd:main]: Offset commit (manual) failed for 1/1 partition(s): Local: Waiting for coordinator: batchPost[0]@30(Local: Waiting for coordinator)
%3|1602837265.489|FAIL|rdkafka#consumer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/1: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
%3|1602837266.930|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
%4|1602837280.447|COMMITFAIL|rdkafka#consumer-1| [thrd:main]: Offset commit (manual) failed for 1/1 partition(s): Local: Waiting for coordinator: batchPost[0]@31(Local: Waiting for coordinator)
%3|1602837302.569|FAIL|rdkafka#consumer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/1: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
%3|1602837305.920|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
```
* message handler still continue to processing messages, the remaining 6 messages were processed.
* turn on kafka again.
* consumer have processed 6 more messages.
* As a result, 16 messages were processed instead of 10.

I used https://github.com/php-enqueue/enqueue-dev with kafka transport.
 * PHP version: 7.4.6
 * librdkafka version: 1.5.0
 * php-rdkafka version: 4.0.3
 * kafka version: 2.6.0

Can someone look into this.
Thanks.

**Comment by Steveb-p** [comment]
I doubt it is something that php-rdkafka do anything about - it's a direct result of:
 - messages being stored internally in librdkafka in queue to speed up processing
 - commit operation being asynchronous, which causes the offset saving request to be sent to Kafka broker, but we're not waiting for response.

To prevent this from happening what you should do is disable automatic commit (I never remember which config parameter it is :laughing: should be `enable.auto.commit`) and commit synchronously (which enqueue-dev actually has a configuration for).

See https://php-enqueue.github.io/transport/kafka/#usage-with-symfony-bundle
```yaml
# app/config/config.yml

enqueue:
    default:
        transport:
            dsn: "rdkafka://"
            global:
                ### Make sure this is unique for each application / consumer group and does not change
                ### Otherwise, Kafka won't be able to track your last offset and will always start according to
                ### `auto.offset.reset` setting.
                ### See Kafka documentation regarding `group.id` property if you want to know more
                group.id: 'foo-app'
                metadata.broker.list: 'example.com:1000'
            topic:
                auto.offset.reset: beginning
            ### Commit async is true by default since version 0.9.9.
            ### It is suggested to set it to true in earlier versions since otherwise consumers become extremely slow,
            ### waiting for offset to be stored on Kafka before continuing.
            commit_async: true
        client: ~
```

also: https://docs.confluent.io/3.2.1/clients/librdkafka/CONFIGURATION_8md.html (look for `enable.auto.commit`)
