### ISSUE TITLE
Publish snapshot to PECL so that we can start testing PHP 8.1 on CI

### ISSUE THREAD

**Issue by ruudk** [php-rdkafka/php-rdkafka#473]
In a few weeks PHP 8.1 will be released. In order for people to prepare their project it would be great if the current `master` could be pushed to PECL as a snapshot release. That will make it easier to install the unreleased version on for example [GitHub Actions using setup-php](https://github.com/shivammathur/setup-php#heavy_plus_sign-php-extension-support).

**Comment by ruudk** [comment]
This seems to work for [setup-php](https://github.com/shivammathur/setup-php/wiki/Add-extension-from-source):

```yaml
- name: Setup PHP with rdkafka from source
  uses: shivammathur/setup-php@v2
  with:
    php-version: '8.1'  
    extensions: rdkafka-arnaud-lb/php-rdkafka@5.x
  env:
    RDKAFKA_LINUX_LIBS: librdkafka-dev
```
